/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { XucreETF__factory } from "./XucreETF__factory";
export { XucreETFV4__factory } from "./XucreETFV4__factory";
